export const CART_LOADING = 'CART_LOADING'
export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT'
export const CART_REMOVE_PRODUCT = 'CART_REMOVE_PRODUCT'
export const CART_ERROR = 'CART_ERROR'

export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING'

export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT'
