export const Actions = {
  ORDER_CREATE_LOADING: 'ORDER_CREATE_LOADING',
  ORDER_CREATE_ERROR: 'ORDER_CREATE_ERROR',
  ORDER_CREATE_SUCCESS: 'ORDER_CREATE_SUCCESS',
  ORDER_GET_LOADING: 'ORDER_GET_LOADING',
  ORDER_GET_ERROR: 'ORDER_GET_ERROR',
  ORDER_GET_SUCCESS: 'ORDER_GET_SUCCESS',
}
