export const Actions = {
  CREATE_ORDER_LOADING: 'CREATE_ORDER_LOADING',
  CREATE_ORDER_ERROR: 'CREATE_ORDER_ERROR',
  CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS',
  GET_ORDER_LOADING: 'GET_ORDER_LOADING',
  GET_ORDER_ERROR: 'GET_ORDER_ERROR',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
}
