export const PRODUCT_LIST_LOADING = 'PRODUCT_LIST_LOADING'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR'

export const PRODUCT_DETAILS_LOADING = 'PRODUCT_DETAILS_LOADING'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_ERROR = 'PRODUCT_DETAILS_ERROR'

export const CREATE_PRODUCT_LOADING = 'CREATE_PRODUCT_LOADING'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'
